### ISSUE TITLE
Merge with upstream

### ISSUE THREAD

**Issue by raghavkhanna** [ethz-asl/dji_onboard_sdk_ros#1]
We should try an pull in upstream changes frequently, once a month should be a good frequency in my opinion. What do you think @inkyusa ?

**Comment by inkyusa** [comment]
That's a great idea reflecting new features and bug fixes regularly.
There are two questions to do this. Who will do this merge and test (including side-effects checking) with a real platform to make sure that the merged one works properly?

I guess this requires time and efforts since the upstream is changing fast by many contributors (more than three people as us). Therefore I would suggest keeping the current 3.2 because it works and update& merge when we need some features from the upstream.

How about this? @raghavkhanna

**Comment by raghavkhanna** [comment]
Agreed :)
