### ISSUE TITLE
Roll Pitch commands in simulation

### ISSUE THREAD

**Issue by suarez-ramon** [ethz-asl/dji_onboard_sdk_ros#5]
Hello,

I am using your sdk for ROS on our DJI matrice 100. I was successful in installing and running the software on the drone. Nevertheless, when testing in simulation with the HIL Dji assistant 2 I am able to send roll and pitch commands by the topic /flourish/fcu/command/roll_pitch... but the behavior is strange. The pitch command, for example, goes in one direction when positive and perpendicular when negative and never reaches the value sent 0.3 for example. I am not using the MPC controller or the msf packages just sending commands via rostopic pub with a rate of 30Hz because if not the virtual rc is shut off. Is this behavior normal in simulation?

Thanks!

**Comment by inkyusa** [comment]
Hello, Suarez
Thank you for your interests in our work and sorry for late reply.

In my understanding, you sent 0.3 (in rad, for example pitch) and quad is not following the command in DJI assistant?
The command you sent is processed in a callback function (cmdCallBack, dji_sdk_node_main.cpp) and scaled, shifted (i.e., add 1024 to make it neutral) and compensated (add some roll trim) since virtual rc (vrc) command is unitless.

Have you check the output topic /yourMavName/vc_cmd and it should show 1433.57 (0.3/0.000865+1024+62.757) for pitch.

While ago, I tested with the H/W in loop simulator but there were some mismatched (I couldn't remember exactly) coordinate systems with one that we are using. Therefore, we tested on a real platform. You also test by swapping signs or coordinate systems (e.g., rotating -90 degree along x-axis).

Hope this help and please let us know if you still face some issues.
Best,

**Comment by inkyusa** [comment]
@suarez-ramon 
Could you please let us know how your things go? or Did you test what we suggested?
I would like to close this issue in a week unless receiving a response from you.
Best,

**Comment by inkyusa** [comment]
I will close this since I haven't received any response from Suarez.
